# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    # ----- 1. build a matrix of job variants ---------------------------
    strategy:
      fail-fast: false          # keep the other job running if one fails
      matrix:
        include:
          # Native host tests (Ubuntu runner)
          - os: ubuntu-latest
            target: native
          # Browser tests + wasm32
          - os: ubuntu-latest
            target: wasm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust tool-chain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown    # adds wasm target once; no-op for native
          components: clippy

      # ---------- Native back-end --------------------------------------
      - name: Run native tests
        if: matrix.target == 'native'
        run: cargo test --all-features --features=native --verbose

      # ---------- Browser/WASM back-end --------------------------------
      - name: Install wasm-bindgen-cli + wasm-pack + Firefox
        if: matrix.target == 'wasm'
        run: |
          cargo install wasm-bindgen-cli --locked
          curl -L https://github.com/rustwasm/wasm-pack/releases/latest/download/wasm-pack-init.sh | bash
          sudo apt-get update -yqq && sudo apt-get install -yqq firefox
      - name: Run browser tests (headless Firefox)
        if: matrix.target == 'wasm'
        run: |
          wasm-pack test --firefox --headless --features=browser

      # ---------- clippy / fmt placeholders (uncomment when ready) -----
      # - name: Lint (clippy)
      #   run: cargo clippy --all-targets --all-features -- -D warnings
      # - name: Style check (rustfmt)
      #   run: cargo fmt -- --check
